samples: "samples.txt"

raw_dir: "/path/to/clean_fastq"

reference:
  gtf: "/path/to/Chicken.gtf"
  star_index: "/path/to/STAR_index"
  enhancer_saf: "/path/to/Enhancer.saf"
  lncrna_saf: "/path/to/lncRNA.saf"
  salmon_index: "/path/to/Salmon_index"
  utr3_bed: "/path/to/Chicken.3utr.bed"

software:
  star: "STAR"
  featurecounts: "featureCounts"
  salmon: "salmon"
  bedtools: "bedtools"
  dapars2: "/path/to/DaPars2_Multi_Sample.py"