import pandas as pd

configfile: "config.yaml"

SAMPLES = pd.read_csv(
    config["samples"], header=None
)[0].drop_duplicates().tolist()

CHROMS = [f"chr{i}" for i in range(1, 39)] + ["chrZ", "chrW"]

GTF = config["reference"]["gtf"]
STAR_INDEX = config["reference"]["star_index"]
ENHANCER_SAF = config["reference"]["enhancer_saf"]
LNCRNA_SAF = config["reference"]["lncrna_saf"]
SALMON_INDEX = config["reference"]["salmon_index"]
UTR3_BED = config["reference"]["utr3_bed"]

RAW = config["raw_dir"]

STAR = config["software"]["star"]
FEATURECOUNTS = config["software"]["featurecounts"]
SALMON = config["software"]["salmon"]
BEDTOOLS = config["software"]["bedtools"]
DAPARS2 = config["software"]["dapars2"]


rule all:
    input:
        expand("0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam", sample=SAMPLES),
        expand("1_gene/{sample}/{sample}_gene.tsv", sample=SAMPLES),
        expand("2_exon/{sample}/{sample}_exon.tsv", sample=SAMPLES),
        expand("3_enhancer/{sample}/{sample}_enhancer.tsv", sample=SAMPLES),
        expand("4_lncRNA/{sample}/{sample}_lncRNA.tsv", sample=SAMPLES),
        expand("5_isoform/{sample}/quant.sf", sample=SAMPLES),
        expand(
            "6_3UTR/all_{chrom}/all_result_temp.{chrom}.txt",
            chrom=CHROMS
        )


# STAR two-pass alignment
rule STAR2pass:
    input:
        gtf=GTF
    output:
        bam="0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam",
        log="0_bam/{sample}/{sample}_Log.final.out"
    threads: 16
    shell:
        """
        mkdir -p 0_bam/{wildcards.sample}

        {STAR} \
          --genomeDir {STAR_INDEX} \
          --sjdbGTFfile {input.gtf} \
          --twopassMode Basic \
          --readFilesIn \
            {RAW}/{wildcards.sample}_clean_1.fq.gz \
            {RAW}/{wildcards.sample}_clean_2.fq.gz \
          --readFilesCommand zcat \
          --runThreadN {threads} \
          --outFileNamePrefix 0_bam/{wildcards.sample}/{wildcards.sample}_ \
          --outSAMtype BAM SortedByCoordinate \
          --outFilterMismatchNmax 3 \
          --outSAMunmapped Within \
          --chimSegmentMin 10 \
          --chimOutType Junctions \
          --chimOutJunctionFormat 1 \
          --outFilterType BySJout \
          --alignSJoverhangMin 8 \
          --alignSJDBoverhangMin 1 \
          --outSAMattrRGline ID:{wildcards.sample} SM:{wildcards.sample} PL:ILLUMINA \
          --outBAMcompression 1
        """


# Gene expression
rule gene_quant:
    input:
        bam="0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam",
        gtf=GTF
    output:
        "1_gene/{sample}/{sample}_gene.tsv"
    threads: 16
    shell:
        """
        mkdir -p 1_gene/{wildcards.sample}

        {FEATURECOUNTS} \
          -T {threads} -p \
          -t exon -g gene_id \
          -a {input.gtf} \
          -o {output} \
          {input.bam}
        """


# Exon expression
rule exon_quant:
    input:
        bam="0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam",
        gtf=GTF
    output:
        "2_exon/{sample}/{sample}_exon.tsv"
    threads: 16
    shell:
        """
        mkdir -p 2_exon/{wildcards.sample}

        {FEATURECOUNTS} \
          -T {threads} -f -p \
          -t exon -g gene_id \
          -a {input.gtf} \
          -o {output} \
          {input.bam}
        """


# Enhancer expression
rule enhancer_quant:
    input:
        bam="0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam",
        saf=ENHANCER_SAF
    output:
        "3_enhancer/{sample}/{sample}_enhancer.tsv"
    threads: 16
    shell:
        """
        mkdir -p 3_enhancer/{wildcards.sample}

        {FEATURECOUNTS} \
          -T {threads} -p \
          -F SAF \
          -a {input.saf} \
          -o {output} \
          {input.bam}
        """


# lncRNA expression
rule lncRNA_quant:
    input:
        bam="0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam",
        saf=LNCRNA_SAF
    output:
        "4_lncRNA/{sample}/{sample}_lncRNA.tsv"
    threads: 16
    shell:
        """
        mkdir -p 4_lncRNA/{wildcards.sample}

        {FEATURECOUNTS} \
          -T {threads} -p \
          -F SAF \
          -a {input.saf} \
          -o {output} \
          {input.bam}
        """


# Transcript / isoform abundance
rule transcript_quant:
    output:
        "5_isoform/{sample}/quant.sf"
    threads: 16
    shell:
        """
        {SALMON} quant \
          -i {SALMON_INDEX} \
          -l A \
          -1 {RAW}/{wildcards.sample}_clean_1.fq.gz \
          -2 {RAW}/{wildcards.sample}_clean_2.fq.gz \
          -p {threads} \
          -o 5_isoform/{wildcards.sample}
        """


# BAM to bedGraph for DaPars2
rule bam2bedgraph:
    input:
        bam="0_bam/{sample}/{sample}_Aligned.sortedByCoord.out.bam",
        log="0_bam/{sample}/{sample}_Log.final.out"
    output:
        bedgraph="6_3UTR/bedgraph/{sample}.bedgraph",
        stat="6_3UTR/bedgraph/{sample}.mapped_reads.txt"
    shell:
        """
        mkdir -p 6_3UTR/bedgraph

        {BEDTOOLS} genomecov \
          -bga -split \
          -ibam {input.bam} \
          > {output.bedgraph}

        depth=$(grep "Uniquely mapped reads number" {input.log} | cut -f2)

        echo -e "{wildcards.sample}\t{output.bedgraph}\t$depth" \
          > {output.stat}
        """


# Combine all sample statistics
rule combinewig:
    input:
        expand(
            "6_3UTR/bedgraph/{sample}.mapped_reads.txt",
            sample=SAMPLES
        )
    output:
        "6_3UTR/all.mapped_reads.txt"
    shell:
        """
        cat {input} > {output}
        """


# Generate DaPars2 config
rule Dapars2_config:
    input:
        stats="6_3UTR/all.mapped_reads.txt",
        utr=UTR3_BED
    output:
        depth="6_3UTR/all_mapped_reads.txt",
        config="6_3UTR/all.config"
    threads: 32
    shell:
        """
        cut -f2,3 {input.stats} > {output.depth}

        wigs=$(cut -f1 {output.depth} | tr '\\n' ',' | sed 's/,$//')

        echo -e \
        "Annotated_3UTR={input.utr}\\n\
Aligned_Wig_files=$wigs\\n\
Output_directory=6_3UTR/all\\n\
Output_result_file=all\\n\
Coverage_threshold=10\\n\
Num_Threads={threads}\\n\
sequencing_depth_file={output.depth}" \
        > {output.config}
        """


# Alternative polyadenylation / 3'UTR usage
rule Dapars2:
    input:
        config="6_3UTR/all.config"
    output:
        "6_3UTR/all_{chrom}/all_result_temp.{chrom}.txt"
    threads: 32
    shell:
        """
        python {DAPARS2} \
          {input.config} \
          {wildcards.chrom}
        """